# /home/deep/esp32-tests/espsdtest/Cargo.toml
[workspace]
resolver = "2"
members = [
    "espsdtest",        # Your main ESP32 application crate
    "espsdtest-tester", # Your new host-side test runner crate
]

# Optional: Define default members if you want `cargo run` at the root
# to run the ESP32 code by default.
default-members = ["espsdtest"]

[profile.release]
opt-level = "s"
lto = true      # Link Time Optimization
codegen-units = 1 # better optimization across units
panic = "abort" # don't include panic formatting
strip = true    # strip symbols

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"